# Settings for the app
app:
  # HTML Title
  title: Vision Zero Community Safety Map
  # Header name
  name: Vision Zero Community Safety Map
  # Meta description that will show up in Google search results
  meta_description: _(Tell NYC DOT about traffic issues in your neighborhood)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 40.71435280167867
      lng: -74.00597310159355
    zoom: 12
    minZoom: 11
    maxZoom: 19
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  doublepark:
    label: _(Double Parking)
    rules:
      - condition: '"{{location_type}}" === "doublepark"'
        icon:
          iconUrl: /static/css/images/markers/dot-doublepark.png
          iconSize: [18, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-doublepark.png
          iconSize: [54, 80]
          iconAnchor: [27, 80]
  jaywalking:
    label: _(Jaywalking)
    rules:
      - condition: '"{{location_type}}" === "jaywalking"'
        icon:
          iconUrl: /static/css/images/markers/dot-jaywalking.png
          iconSize: [18, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-jaywalking.png
          iconSize: [54, 80]
          iconAnchor: [27, 80]
  longcross:
    label: _(Long Cross)
    rules:
      - condition: '"{{location_type}}" === "longcross"'
        icon:
          iconUrl: /static/css/images/markers/dot-longcross.png
          iconSize: [18, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-longcross.png
          iconSize: [54, 80]
          iconAnchor: [27, 80]
  longwait:
    label: _(Long Wait)
    rules:
      - condition: '"{{location_type}}" === "longwait"'
        icon:
          iconUrl: /static/css/images/markers/dot-longwait.png
          iconSize: [18, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-longwait.png
          iconSize: [54, 80]
          iconAnchor: [27, 80]          
  notime:
    label: _(No Time)
    rules:
      - condition: '"{{location_type}}" === "notime"'
        icon:
          iconUrl: /static/css/images/markers/dot-notime.png
          iconSize: [18, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-notime.png
          iconSize: [54, 80]
          iconAnchor: [27, 80]
  redlight:
    label: _(Red Light)
    rules:
      - condition: '"{{location_type}}" === "redlight"'
        icon:
          iconUrl: /static/css/images/markers/dot-redlight.png
          iconSize: [18, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-redlight.png
          iconSize: [54, 80]
          iconAnchor: [27, 80]
  speeding:
    label: _(Speeding)
    rules:
      - condition: '"{{location_type}}" === "speeding"'
        icon:
          iconUrl: /static/css/images/markers/dot-speeding.png
          iconSize: [18, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-speeding.png
          iconSize: [54, 80]
          iconAnchor: [27, 80]
  visibility:
    label: _(Visibility)
    rules:
      - condition: '"{{location_type}}" === "visibility"'
        icon:
          iconUrl: /static/css/images/markers/dot-visibility.png
          iconSize: [18, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-visibility.png
          iconSize: [54, 80]
          iconAnchor: [27, 80]
  yield:
    label: _(Failure to yield)
    rules:
      - condition: '"{{location_type}}" === "yield"'
        icon:
          iconUrl: /static/css/images/markers/dot-yield.png
          iconSize: [18, 18]
          iconAnchor: [9, 9]
        focus_icon:
          iconUrl: /static/css/images/markers/marker-yield.png
          iconSize: [54, 80]
          iconAnchor: [27, 80]
activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Share a problem)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(Show as list)
  show_map_button_label: _(Show on map)
  action_text: _(added)
  title: _(Describe the issue at this intersection)
  help_text: _(Place the map marker at the intersection and tell us more about the problem you observed.)
  anonymous_name: _(Someone)
  submit_button_label: _(Put on map)
  items:
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Your Email)
      type: text
      name: private-submitter_email
      optional: true
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30
    - prompt: _(Intersection)
      type: text
      name: name
      attrs:
        - key: placeholder
          value: _(Location Name)
        - key: size
          value: 30
        - key: required
    - prompt: _(Observered problem)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Double Parking)
          value: doublepark
        - label: _(Jaywalking)
          value: jaywalking
        - label: _(Long Cross)
          value: longcross
        - label: _(Long Wait)
          value: longwait
        - label: _(No Time)
          value: notime
        - label: _(Red Light)
          value: redlight
        - label: _(Speeding)
          value: speeding
        - label: _(Visibility)
          value: visibility
        - label: _(Yield)
          value: yield
      name: location_type
      attrs:
        - key: required
    - prompt: _(Provide more information about the problem)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description...)

survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Support)
  response_name: _(support)
  response_plural_name: _(supports)
  action_text: supported
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
    # start_page: true

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email