# Settings for the app
app:
  # HTML Title
  title: Vision Zero Community Safety Map
  # Header name
  name: Vision Zero Community Safety Map
  # Meta description that will show up in Google search results
  meta_description: _(Vision Zero is the City's goal for ending traffic deaths and injuries on our streets. To accomplish this, we need everyone's participation and input.)

  # When the map loads, existing places will be loaded in chunks. By default,
  # the size of the chunks will be a reasonable default dictated by the API
  # server. If you would like to override the chunk size, use this setting:
  # places_page_size: 100

  # Optional. List view is supported by default. Set to false to disable.
  list_enabled: false

# Settings for map and layer configs
map:
  geolocation_enabled: true
  geolocation_onload: false
  options:
    center:
      lat: 40.71435280167867
      lng: -74.00597310159355
    zoom: 12
    minZoom: 11
    maxZoom: 19
  layers:
    - url: http://{s}.tiles.mapbox.com/v3/openplans.map-dmar86ym/{z}/{x}/{y}.png
      attribution: '&copy; OpenStreetMap contributors, CC-BY-SA. <a href="http://mapbox.com/about/maps" target="_blank">Terms &amp; Feedback</a>'
    - url: http://{s}.tiles.mapbox.com/v3/openplans.162-Vision-Zero/{z}/{x}/{y}.png

# The keys show up in the dropdown list when you are adding a new place
# The values map the place type to map icons (defined below).
place_types:
  doublepark:
    label: _(Double parking)
    rules:
      - condition: '"{{location_type}}" === "doublepark" && {{map.zoom}} < 15 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-doublepark-sm.png
          iconSize: [10, 10]
          iconAnchor: [5, 5]
      - condition: '"{{location_type}}" === "doublepark" && {{map.zoom}} >= 15 && {{map.zoom}} < 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-doublepark-m.png
          iconSize: [22, 22]
          iconAnchor: [11, 11]
      - condition: '"{{location_type}}" === "doublepark" && {{map.zoom}} >= 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/icon-dot-doublepark.png
          iconSize: [32, 33]
          iconAnchor: [16, 16]
      - condition: '"{{location_type}}" === "doublepark" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-doublepark.png
          iconSize: [54, 80]
          iconAnchor: [27, 77]
          shadowUrl: /static/css/images/markers/marker-shadow.png
          shadowSize: [68, 31]
          shadowAnchor: [34, 31]
  jaywalking:
    label: _(Jaywalking)
    rules:
      - condition: '"{{location_type}}" === "jaywalking" && {{map.zoom}} < 15 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-jaywalking-sm.png
          iconSize: [10, 10]
          iconAnchor: [5, 5]
      - condition: '"{{location_type}}" === "jaywalking" && {{map.zoom}} >= 15 && {{map.zoom}} < 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-jaywalking-m.png
          iconSize: [22, 22]
          iconAnchor: [11, 11]
      - condition: '"{{location_type}}" === "jaywalking" && {{map.zoom}} >= 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/icon-dot-jaywalking.png
          iconSize: [32, 33]
          iconAnchor: [16, 16]
      - condition: '"{{location_type}}" === "jaywalking" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-jaywalking.png
          iconSize: [54, 80]
          iconAnchor: [27, 77]
          shadowUrl: /static/css/images/markers/marker-shadow.png
          shadowSize: [68, 31]
          shadowAnchor: [34, 31]
  longcross:
    label: _(Long distance to cross)
    rules:
      - condition: '"{{location_type}}" === "longcross" && {{map.zoom}} < 15 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-longcross-sm.png
          iconSize: [10, 10]
          iconAnchor: [5, 5]
      - condition: '"{{location_type}}" === "longcross" && {{map.zoom}} >= 15 && {{map.zoom}} < 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-longcross-m.png
          iconSize: [22, 22]
          iconAnchor: [11, 11]
      - condition: '"{{location_type}}" === "longcross" && {{map.zoom}} >= 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/icon-dot-longcross.png
          iconSize: [32, 33]
          iconAnchor: [16, 16]
      - condition: '"{{location_type}}" === "longcross" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-longcross.png
          iconSize: [54, 80]
          iconAnchor: [27, 77]
          shadowUrl: /static/css/images/markers/marker-shadow.png
          shadowSize: [68, 31]
          shadowAnchor: [34, 31]
  longwait:
    label: _(Long wait to cross)
    rules:
      - condition: '"{{location_type}}" === "longwait"  && {{map.zoom}} < 15 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-longwait-sm.png
          iconSize: [10, 10]
          iconAnchor: [5, 5]
      - condition: '"{{location_type}}" === "longwait"  && {{map.zoom}} >= 15 && {{map.zoom}} < 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-longwait-m.png
          iconSize: [22, 22]
          iconAnchor: [11, 11]
      - condition: '"{{location_type}}" === "longwait" && {{map.zoom}} >= 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/icon-dot-longwait.png
          iconSize: [32, 33]
          iconAnchor: [16, 16]
      - condition: '"{{location_type}}" === "longwait" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-longwait.png
          iconSize: [54, 80]
          iconAnchor: [27, 77]
          shadowUrl: /static/css/images/markers/marker-shadow.png
          shadowSize: [68, 31]
          shadowAnchor: [34, 31]
  notime:
    label: _(Not enough time to cross)
    rules:
      - condition: '"{{location_type}}" === "notime" && {{map.zoom}} < 15 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-notime-sm.png
          iconSize: [10, 10]
          iconAnchor: [5, 5]
      - condition: '"{{location_type}}" === "notime" && {{map.zoom}} >= 15 && {{map.zoom}} < 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-notime-m.png
          iconSize: [22, 22]
          iconAnchor: [11, 11]
      - condition: '"{{location_type}}" === "notime" && {{map.zoom}} >= 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/icon-dot-notime.png
          iconSize: [32, 33]
          iconAnchor: [16, 16]
      - condition: '"{{location_type}}" === "notime" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-notime.png
          iconSize: [54, 80]
          iconAnchor: [27, 77]
          shadowUrl: /static/css/images/markers/marker-shadow.png
          shadowSize: [68, 31]
          shadowAnchor: [34, 31]
  redlight:
    label: _(Red light running)
    rules:
      - condition: '"{{location_type}}" === "redlight" && {{map.zoom}} < 15 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-redlight-sm.png
          iconSize: [10, 10]
          iconAnchor: [5, 5]
      - condition: '"{{location_type}}" === "redlight" && {{map.zoom}} >= 15 && {{map.zoom}} < 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-redlight-m.png
          iconSize: [22, 22]
          iconAnchor: [11, 11]
      - condition: '"{{location_type}}" === "redlight" && {{map.zoom}} >= 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/icon-dot-redlight.png
          iconSize: [32, 33]
          iconAnchor: [16, 16]
      - condition: '"{{location_type}}" === "redlight" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-redlight.png
          iconSize: [54, 80]
          iconAnchor: [27, 77]
          shadowUrl: /static/css/images/markers/marker-shadow.png
          shadowSize: [68, 31]
          shadowAnchor: [34, 31]
  speeding:
    label: _(Speeding)
    rules:
      - condition: '"{{location_type}}" === "speeding" && {{map.zoom}} < 15 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-speeding-sm.png
          iconSize: [10, 10]
          iconAnchor: [5, 5]
      - condition: '"{{location_type}}" === "speeding" && {{map.zoom}} >= 15 && {{map.zoom}} < 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-speeding-m.png
          iconSize: [22, 22]
          iconAnchor: [11, 11]
      - condition: '"{{location_type}}" === "speeding" && {{map.zoom}} >= 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/icon-dot-speeding.png
          iconSize: [32, 33]
          iconAnchor: [16, 16]
      - condition: '"{{location_type}}" === "speeding" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-speeding.png
          iconSize: [54, 80]
          iconAnchor: [27, 77]
          shadowUrl: /static/css/images/markers/marker-shadow.png
          shadowSize: [68, 31]
          shadowAnchor: [34, 31]
  visibility:
    label: _(Poor visibility)
    rules:
      - condition: '"{{location_type}}" === "visibility" && {{map.zoom}} < 15 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-visibility-sm.png
          iconSize: [10, 10]
          iconAnchor: [5, 5]
      - condition: '"{{location_type}}" === "visibility" && {{map.zoom}} >= 15 && {{map.zoom}} < 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-visibility-m.png
          iconSize: [22, 22]
          iconAnchor: [11, 11]
      - condition: '"{{location_type}}" === "visibility" && {{map.zoom}} >= 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/icon-dot-visibility.png
          iconSize: [32, 33]
          iconAnchor: [16, 16]
      - condition: '"{{location_type}}" === "visibility" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-visibility.png
          iconSize: [54, 80]
          iconAnchor: [27, 77]
          shadowUrl: /static/css/images/markers/marker-shadow.png
          shadowSize: [68, 31]
          shadowAnchor: [34, 31]
  yield:
    label: _(Failure to yield)
    rules:
      - condition: '"{{location_type}}" === "yield" && {{map.zoom}} < 15 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-yield-sm.png
          iconSize: [10, 10]
          iconAnchor: [5, 5]
      - condition: '"{{location_type}}" === "yield" && {{map.zoom}} >= 15 && {{map.zoom}} < 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-yield-m.png
          iconSize: [22, 22]
          iconAnchor: [11, 11]
      - condition: '"{{location_type}}" === "yield" && {{map.zoom}} >= 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/icon-dot-yield.png
          iconSize: [32, 33]
          iconAnchor: [16, 16]
      - condition: '"{{location_type}}" === "yield" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-yield.png
          iconSize: [54, 80]
          iconAnchor: [27, 77]
          shadowUrl: /static/css/images/markers/marker-shadow.png
          shadowSize: [68, 31]
          shadowAnchor: [34, 31]
  bike:
    label: _(Cyclist behavior)
    rules:
      - condition: '"{{location_type}}" === "bike"&& {{map.zoom}} < 15 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-bike-sm.png
          iconSize: [10, 10]
          iconAnchor: [5, 5]
      - condition: '"{{location_type}}" === "bike" && {{map.zoom}} >= 15 && {{map.zoom}} < 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-bike-m.png
          iconSize: [22, 22]
          iconAnchor: [11, 11]
      - condition: '"{{location_type}}" === "bike" && {{map.zoom}} >= 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/icon-dot-bike.png
          iconSize: [32, 33]
          iconAnchor: [16, 16]
      - condition: '"{{location_type}}" === "bike" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-bike.png
          iconSize: [54, 80]
          iconAnchor: [27, 77]
          shadowUrl: /static/css/images/markers/marker-shadow.png
          shadowSize: [68, 31]
          shadowAnchor: [34, 31]
  other:
    label: _(Other)
    rules:
      - condition: '"{{location_type}}" === "other" && {{map.zoom}} < 15 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-unknown-sm.png
          iconSize: [10, 10]
          iconAnchor: [5, 5]
      - condition: '"{{location_type}}" === "other" && {{map.zoom}} >= 15 && {{map.zoom}} < 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/dot-unknown-m.png
          iconSize: [22, 22]
          iconAnchor: [11, 11]
      - condition: '"{{location_type}}" === "other" && {{map.zoom}} >= 17 && {{layer.focused}} === false'
        icon:
          iconUrl: /static/css/images/markers/icon-dot-unknown.png
          iconSize: [32, 33]
          iconAnchor: [16, 16]
      - condition: '"{{location_type}}" === "other" && {{layer.focused}} === true'
        icon:
          iconUrl: /static/css/images/markers/marker-unknown.png
          iconSize: [54, 80]
          iconAnchor: [27, 77]
          shadowUrl: /static/css/images/markers/marker-shadow.png
          shadowSize: [68, 31]
          shadowAnchor: [34, 31]
activity:
  # Optional. Activity is supported by default. Set to false to disable.
  enabled: true
  # How often to refresh the activity list, in milliseconds.
  interval: 30000

place:
  adding_supported: true
  add_button_label: _(Share an Issue)
  # Labels for the buttons that toggle the map and list views
  show_list_button_label: _(Show as list)
  show_map_button_label: _(Show on map)
  action_text: _(reported)
  title: _(Describe the issue)
  help_text: _( )
  anonymous_name: _(Someone)
  submit_button_label: _(Put on map)
  items:
    - prompt: _(Your Name)
      type: text
      name: submitter_name
      optional: true
      attrs:
        - key: placeholder
          value: _(Name)
        - key: size
          value: 30
    - prompt: _(Observed issue)
      type: select
      options:
        - label: _(Choose One)
          value: ''
        - label: _(Double parking)
          value: doublepark
        - label: _(Jaywalking)
          value: jaywalking
        - label: _(Long distance to cross)
          value: longcross
        - label: _(Long wait to cross)
          value: longwait
        - label: _(Not enough time to cross)
          value: notime
        - label: _(Red light running)
          value: redlight
        - label: _(Speeding)
          value: speeding
        - label: _(Poor visibility)
          value: visibility
        - label: _(Failure to yield)
          value: yield
        - label: _(Cyclist behavior)
          value: bike
        - label: _(Other)
          value: other
      name: location_type
      attrs:
        - key: required
    - prompt: _(Provide more information about the issue)
      type: textarea
      name: description
      optional: true
      attrs:
        - key: placeholder
          value: _(Description...)
    - prompt: _(Your Email)
      type: text
      name: private-submitter_email
      optional: true
      attrs:
        - key: placeholder
          value: _(Email address)
        - key: size
          value: 30
survey:
  submission_type: comments

  # Response config
  show_responses: true
  response_name: _(comment)
  response_plural_name: _(comments)
  action_text: _(commented on)
  anonymous_name: _(Someone)

  # Survey form config
  title: _(Leave a Comment)
  form_link_text: _(Leave a Comment)
  submit_btn_text: _(Comment)
  items:
    - prompt: _(Comment)
      label: _(Comment)
      type: textarea
      name: comment
      attrs:
        - key: required
    - prompt: _(Your Name)
      type: text
      name: submitter_name

support:
  submission_type: support
  submit_btn_text: _(Agree)
  response_name: _(agree)
  response_plural_name: _(agree)
  action_text: agreed
  anonymous_name: _(Someone)

pages:
  - title: _(About)
    slug: about
    name: overview
  - title: _(Attend a workshop)
    slug: workshops
    name: why

notifications:
  on_new_place: true
  submitter_email_field: private-submitter_email